name: Makefile CI

on:
  schedule:
  - cron: "0 4 * * 0"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup jdk-17
      uses: actions/setup-java@main
      with:
        java-version: 17
        distribution: 'adopt'
    
    - name: update submodule
      run: git submodule update --init --recursive
    
    - name: build release
      run: make release

    - uses: actions/upload-artifact@v2
      with:
        # NYI get version from version-file
        path: fuzion_language_server_0.3.0.zip


